<?php

namespace ContainerUF2MZ0M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E8ONmreService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E8ONmre' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E8ONmre'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ControladorCasinoController::banear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::checkAllUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::checkBannedUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::checkUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::desbanear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::edit' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::eliminar' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::makeAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::nuevo' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::verifyUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ControladorCasinoController:banear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:checkAllUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:checkBannedUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:checkUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:desbanear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:edit' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:eliminar' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:makeAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:nuevo' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:verifyUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ControladorCasinoController::banear' => '?',
            'App\\Controller\\ControladorCasinoController::checkAllUsers' => '?',
            'App\\Controller\\ControladorCasinoController::checkBannedUsers' => '?',
            'App\\Controller\\ControladorCasinoController::checkUser' => '?',
            'App\\Controller\\ControladorCasinoController::desbanear' => '?',
            'App\\Controller\\ControladorCasinoController::edit' => '?',
            'App\\Controller\\ControladorCasinoController::eliminar' => '?',
            'App\\Controller\\ControladorCasinoController::makeAdm' => '?',
            'App\\Controller\\ControladorCasinoController::nuevo' => '?',
            'App\\Controller\\ControladorCasinoController::verifyUser' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ControladorCasinoController:banear' => '?',
            'App\\Controller\\ControladorCasinoController:checkAllUsers' => '?',
            'App\\Controller\\ControladorCasinoController:checkBannedUsers' => '?',
            'App\\Controller\\ControladorCasinoController:checkUser' => '?',
            'App\\Controller\\ControladorCasinoController:desbanear' => '?',
            'App\\Controller\\ControladorCasinoController:edit' => '?',
            'App\\Controller\\ControladorCasinoController:eliminar' => '?',
            'App\\Controller\\ControladorCasinoController:makeAdm' => '?',
            'App\\Controller\\ControladorCasinoController:nuevo' => '?',
            'App\\Controller\\ControladorCasinoController:verifyUser' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
