<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE0AibSF\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE0AibSF/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerE0AibSF.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerE0AibSF\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerE0AibSF\App_KernelProdContainer([
    'container.build_hash' => 'E0AibSF',
    'container.build_id' => '37b65bf0',
    'container.build_time' => 1699958355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE0AibSF');
