<?php

namespace ContainerE0AibSF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContactoRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ContactoRepository' shared autowired service.
     *
     * @return \App\Repository\ContactoRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ContactoRepository'] = new \App\Repository\ContactoRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
