<?php

namespace Container5xKehzZ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LT1wOu2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LT1wOu2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LT1wOu2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ControladorCasinoController::banear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::checkAllUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::checkBannedUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::checkUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::contact' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::denegarVerificacion' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::desbanear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::edit' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::eliminar' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::makeAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::nuevo' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::removeAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::verificarUserAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController::verifyUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PerfilController::perfilUser' => ['privates', '.service_locator.xigBV3B', 'get_ServiceLocator_XigBV3BService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\ControladorCasinoController:banear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:checkAllUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:checkBannedUsers' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:checkUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:contact' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:denegarVerificacion' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:desbanear' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:edit' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:eliminar' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:makeAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:nuevo' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:removeAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:verificarUserAdm' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\ControladorCasinoController:verifyUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\PerfilController:perfilUser' => ['privates', '.service_locator.xigBV3B', 'get_ServiceLocator_XigBV3BService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\ControladorCasinoController::banear' => '?',
            'App\\Controller\\ControladorCasinoController::checkAllUsers' => '?',
            'App\\Controller\\ControladorCasinoController::checkBannedUsers' => '?',
            'App\\Controller\\ControladorCasinoController::checkUser' => '?',
            'App\\Controller\\ControladorCasinoController::contact' => '?',
            'App\\Controller\\ControladorCasinoController::denegarVerificacion' => '?',
            'App\\Controller\\ControladorCasinoController::desbanear' => '?',
            'App\\Controller\\ControladorCasinoController::edit' => '?',
            'App\\Controller\\ControladorCasinoController::eliminar' => '?',
            'App\\Controller\\ControladorCasinoController::makeAdm' => '?',
            'App\\Controller\\ControladorCasinoController::nuevo' => '?',
            'App\\Controller\\ControladorCasinoController::removeAdm' => '?',
            'App\\Controller\\ControladorCasinoController::verificarUserAdm' => '?',
            'App\\Controller\\ControladorCasinoController::verifyUser' => '?',
            'App\\Controller\\PerfilController::perfilUser' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ControladorCasinoController:banear' => '?',
            'App\\Controller\\ControladorCasinoController:checkAllUsers' => '?',
            'App\\Controller\\ControladorCasinoController:checkBannedUsers' => '?',
            'App\\Controller\\ControladorCasinoController:checkUser' => '?',
            'App\\Controller\\ControladorCasinoController:contact' => '?',
            'App\\Controller\\ControladorCasinoController:denegarVerificacion' => '?',
            'App\\Controller\\ControladorCasinoController:desbanear' => '?',
            'App\\Controller\\ControladorCasinoController:edit' => '?',
            'App\\Controller\\ControladorCasinoController:eliminar' => '?',
            'App\\Controller\\ControladorCasinoController:makeAdm' => '?',
            'App\\Controller\\ControladorCasinoController:nuevo' => '?',
            'App\\Controller\\ControladorCasinoController:removeAdm' => '?',
            'App\\Controller\\ControladorCasinoController:verificarUserAdm' => '?',
            'App\\Controller\\ControladorCasinoController:verifyUser' => '?',
            'App\\Controller\\PerfilController:perfilUser' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
