<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZ4HuoOx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZ4HuoOx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZ4HuoOx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZ4HuoOx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZ4HuoOx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Z4HuoOx',
    'container.build_id' => '23e3c0f9',
    'container.build_time' => 1708135451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZ4HuoOx');
