<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTrCY63K\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTrCY63K/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTrCY63K.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTrCY63K\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTrCY63K\App_KernelDevDebugContainer([
    'container.build_hash' => 'TrCY63K',
    'container.build_id' => '5a168b95',
    'container.build_time' => 1708070757,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTrCY63K');
