<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUF2MZ0M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUF2MZ0M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUF2MZ0M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUF2MZ0M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUF2MZ0M\App_KernelDevDebugContainer([
    'container.build_hash' => 'UF2MZ0M',
    'container.build_id' => '1d239619',
    'container.build_time' => 1698222633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUF2MZ0M');
